apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: cart-mapping
spec:
  gatewayRef:
    name: cluster-gateway
    namespace: default
  routeConfigRef:
    name: cart-route-config